<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKg7ryul\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKg7ryul/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerKg7ryul.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerKg7ryul\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerKg7ryul\appProdProjectContainer([
    'container.build_hash' => 'Kg7ryul',
    'container.build_id' => 'a573b22e',
    'container.build_time' => 1674041935,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKg7ryul');
